code/newdeal/urls.py
from articles import views as articles_view
from django.conf import settings
from django.contrib import admin
from django.urls import include, path  # , re_path
from search import views as search_views
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

# from rest_framework import routers

# router = routers.DefaultRouter()

urlpatterns = [
    path('django-admin/', admin.site.urls),

    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    path('search/', search_views.search, name='search'),
    path('search-all/', articles_view.search_all, name='search-all'),

    path('sna/', include('sna.urls', namespace='sna')),

    # path('api/', include(router.urls)),

]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r"^pages/", include(wagtail_urls)),
]

# WARNING tests fail on error for djdt resolution
# if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [path('_djdt/', include(debug_toolbar.urls)),] + urlpatterns

code/sna/urls.py
from django.urls import include, path

from .views import views

app_name = 'sna'

api_patterns = [
    path('gdp/units/', views.get_units, name='api_get_units'),
    path('gdp/token/', views.get_token, name='api_get_token'),
    path('gdp/categories/', views.get_categories_tree, name='api_categories'),
    path('gdp/years/<str:token>', views.get_years, name='api_years'),
    path('gdp/data/byYear/<int:year>', views.get_data_by_year, name='api_data_by_year'),
    path('gdp/data/<str:token>/byCategory/<int:categoryId>/series',
         views.get_data_series_by_category,
         name='api_data_series_by_category'),
]


urlpatterns = [
    path('', views.index, name='sna_index'),
    path('balance/', views.balance_sheet, name='balance_sheet'),  # TODO Replace with Wagtail page
    path('upload', views.upload_file),
    path('api/v1/', include(api_patterns))
]

code/newdeal/templates/base.html
<!DOCTYPE html>
{% load static wagtailuserbar wagtailimages_tags  wagtailcore_tags sniplates %}
<html class="no-js" lang="ru-RU">
  <head>
    <meta name="description" content="">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="robots" content="{% if not DEBUG %}index, follow{% else %}noindex, nofollow{% endif %}">
    <meta name="author" content="Пролетариат">
    {% if settings.core.NewDealSettings.favicon %}
    <link rel="icon" type="image/png" href="{{ settings.core.NewDealSettings.favicon.url }}" />
    {% else %}
    <link rel="icon" type="image/png" href="{% static 'images/favicon_256.png' %}" />
    {% endif %}
    {% comment %}<meta property="og:url" content="https://site.ru">{% endcomment %}
    <meta property="og:title" content="">
    <meta property="og:image" content="assets/images/og/og-images.jpg">
    <meta property="og:image:type" content="image/jpeg">
    <meta property="og:image:width" content="640">
    <meta property="og:image:height" content="442">
    <meta property="og:description" content="">
    <meta property="og:site_name" content="Site-name">
    {% block extra_head %}{% endblock extra_head %}
    {% comment %}<link rel="canonical" href="https://site.ru">{% endcomment %}
    <title>
    {% block title %}
        {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
    {% endblock %}
    {% block title_suffix %}
        {% with self.get_site.site_name as site_name %}
            {% if site_name %}- {{ site_name }}{% endif %}
        {% endwith %}
    {% endblock %}
    </title>
    {% comment %}<link href="favicon.ico" rel="shortcut icon" type="image/x-icon">{% endcomment %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendor.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/newdeal.min.css' %}">
    {% block extra_css %}
        {# Override this in templates to add extra stylesheets #}
    {% endblock %}
    {% if settings.core.NewDealSettings.fontawesome_kit %}
    <script src="https://kit.fontawesome.com/{{ settings.core.NewDealSettings.fontawesome_kit }}.js" crossorigin="anonymous"></script>
    {% endif %}
  </head>

  <body>
    <div class="wrapper">
      <header class="header">
        <div class="container">
          <div class="header__wrapper">
            <div class="header__logo logo">
                <a class="logo__link" href="/">
                    {% with settings.core.NewDealSettings.main_logo as logo %}
                    {% if logo %}
                    {% image logo max-100x80 %}
                    {% else %}
                    <img class="logo__img" src="{% static 'images/header/logo.png' %}" alt="New Deal">
                    {% endif %}
                    {% endwith %}
                </a>
            </div>
            {% comment %}Search{% endcomment %}
            <div class="header__search search">
              {% url 'search-all' as default_search_url %}
              <form class="search__form" action="{{ search_url|default:default_search_url }}" method="get" name="search__form">
                <div class="search__wrapper">
                  <input class="search__inp" type="text" name="q" {% if search_query %}value="{{ search_query }}"{% endif %}>
                  <button class="search__btn">
                    <svg class="search__svg" version="1.1" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 26.1 26.1" xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 26.1 26.1">
                      <path fill="#818181" d="m25.806,22.9l-5.4-5.4c-0.2-0.2-0.2-0.4-0.1-0.6 1.1-1.7 1.7-3.7 1.7-5.9 0-6.1-4.9-11-11-11s-11,4.9-11,11 4.9,11 11,11c2.2,0 4.2-0.6 5.9-1.7 0.2-0.1 0.5-0.1 0.6,0.1l5.4,5.4c0.4,0.4 1,0.4 1.4,0l1.4-1.4c0.5-0.5 0.5-1.1 0.1-1.5zm-14.7-4.9c-3.9,0-7-3.1-7-7s3.1-7 7-7 7,3.1 7,7-3.1,7-7,7z"></path>
                    </svg>
                  </button>
                </div>
              </form>
            </div>
            {% comment %} navigation menu {% endcomment %}
            <nav class="header__main-menu main-menu">
              <div class="main-menu__hamburger">
                {% comment %} Hamburger svg {% endcomment %}
                <svg id="Слой_1" style="enable-background:new 0 0 139 139;" version="1.1" viewbox="0 40 140 60" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <style type="text/css">.st0{fill:none;stroke:#818181;stroke-width:6;stroke-miterlimit:10;}</style>
                    <line class="st0" id="XMLID_6_" x1="26.5" x2="112.5" y1="46.3" y2="46.3"></line>
                    <line class="st0" id="XMLID_9_" x1="26.5" x2="112.5" y1="92.7" y2="92.7"></line>
                    <line class="st0" id="XMLID_8_" x1="26.5" x2="112.5" y1="69.5" y2="69.5"></line>
                </svg>
                {% comment %} end of svg {% endcomment %}
              </div>
              <ul class="main-menu__list">
                <li class="main-menu__item main-menu__item_logo logo">
                <a class="logo__link" href="/">
                    {% with settings.core.NewDealSettings.main_logo as logo %}
                    {% if logo %}
                    {% image logo max-100x70 %}
                    {% else %}
                    <img class="logo__img" src="{% static 'images/header/logo.png' %}" alt="New Deal">
                    {% endif %}
                    {% endwith %}
                </a>
                </li>
                <li class="main-menu__item"><a class="main-menu__link txt txt_font_os txt_size_15" href='{% slugurl "home" %}'>Главная</a></li>
                <li class="main-menu__item"><a class="main-menu__link txt txt_font_os txt_size_15" href='{% slugurl "news" %}'>Новости</a></li>
                <li class="main-menu__item"><a class="main-menu__link txt txt_font_os txt_size_15" href='{% slugurl "articles" %}'>Статьи</a></li>
                <li class="main-menu__item"><a class="main-menu__link txt txt_font_os txt_size_15" href="#">Графики</a>
                  <ul class="main-menu__sub-list">
                    <li class="main-menu__sub-item"><a class="main-menu__sub-link txt txt_font_os txt_size_13" href="{% url 'sna:sna_index' %}">ВВП России</a></li>
                    <li class="main-menu__sub-item"><a class="main-menu__sub-link txt txt_font_os txt_size_13" href="{% url 'sna:balance_sheet' %}">Balance Sheet Visualizer</a></li>
                    <li class="main-menu__sub-item"><a class="main-menu__sub-link txt txt_font_os txt_size_13" href="#">И еще одна</a></li>
                    <li class="main-menu__sub-item"><a class="main-menu__sub-link txt txt_font_os txt_size_13" href="#">Четвертая</a></li>
                  </ul>
                </li>
                <li class="main-menu__item"><a class="main-menu__link txt txt_font_os txt_size_15" href="#">Статистика</a></li>
                {% if user.is_staff %}
                <li class="main-menu__item"><a class="main-menu__link txt txt_font_os txt_size_15" href="#">Управление</a>
                  <ul class="main-menu__sub-list">
                    <li class="main-menu__sub-item"><a class="main-menu__sub-link txt txt_font_os txt_size_13" href="/admin/">Wagtail</a></li>
                    <li class="main-menu__sub-item"><a class="main-menu__sub-link txt txt_font_os txt_size_13" href="/django-admin/">Django</a></li>
                  </ul>
                </li>
                {% endif %}
                <li class="main-menu__item main-menu__item_search">
                {% comment %} drawer mobile search {% endcomment %}
                  <div class="search">
                    <div class="search__desc txt txt_font_p txt_size_18"><span>Поиск по сайту:</span></div>
                    <form class="search__form" action="{{ search_url|default:default_search_url }}" method="get" name="search__form">
                      <div class="search__wrapper">
                        <input class="search__inp" type="text" name="q">
                        <button class="search__btn">
                          <svg class="search__svg" version="1.1" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 26.1 26.1" xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 26.1 26.1">
                            <path fill="#818181" d="m25.806,22.9l-5.4-5.4c-0.2-0.2-0.2-0.4-0.1-0.6 1.1-1.7 1.7-3.7 1.7-5.9 0-6.1-4.9-11-11-11s-11,4.9-11,11 4.9,11 11,11c2.2,0 4.2-0.6 5.9-1.7 0.2-0.1 0.5-0.1 0.6,0.1l5.4,5.4c0.4,0.4 1,0.4 1.4,0l1.4-1.4c0.5-0.5 0.5-1.1 0.1-1.5zm-14.7-4.9c-3.9,0-7-3.1-7-7s3.1-7 7-7 7,3.1 7,7-3.1,7-7,7z"></path>
                          </svg>
                        </button>
                      </div>
                    </form>
                  </div>
                </li>
               {% comment %} end of nav items {% endcomment %}
              </ul>
            </nav>
            {% comment %} end of header items {% endcomment %}
          </div>
        </div>
      </header>
      <main class="main">
        {% block main %} {% load_widgets common="sniplates/sniplates_common.html" %}
        <section class="section {% block section %}placeholder{% endblock section %}">
          <div class="container">
            <div class="section__head">
              <div class="section__title title">
                {% block header1 %}<h1>{{ page.title }}</h1>{% endblock header1 %}
                {% block header2 %}{% endblock header2 %}
                {% wagtailuserbar %}
              </div>
              {% block subtitle %}
              {% if DEBUG %}
              <div class="section__subtitle">
                 <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. (only in debug)</span>
              </div>
              {% endif %}
              {% endblock subtitle %}

              {% if paginator %}
              {% widget "common:pagination" page_obj=page_obj paginator=paginator search_query=search_query %}
              {% endif %}

            </div>
            <div class="section__body">
              <div class="filler txt txt_font_os txt_size_13">
                {% block content %}
                {% endblock %}
              </div>

              {% if paginator %}
              {% widget "common:pagination" page_obj=page_obj paginator=paginator search_query=search_query %}
              {% endif %}

            </div>
          </div>
        </section>
        {% endblock main %}
      </main>
    </div>
    {% include 'base_footer.html' %}
  </body>
    <script src="{% static 'js/vendor.min.js' %}"></script>
    <script src="{% static 'js/newdeal.min.js' %}"></script>
    {% block extra_js %}
        {# Override this in templates to add extra javascript #}
    {% endblock %}
</html>

code/newdeal/templates/base_footer.html
{% load static wagtailimages_tags nd_core_tags wagtailcore_tags %}
<footer class="footer">
  <div class="footer__wrapper">
    <div class="footer__logo logo">
        <a class="logo__link" href="/">
        {% with settings.core.NewDealSettings.main_logo as logo %}
            {% if logo %}
            {% image logo max-150x80 %}
            {% else %}
            <img class="logo__img" src="{% static 'images/header/logo.png' %}" alt="New Deal" />
            {% endif %}
        {% endwith %}
        </a>
    </div>
    <div class="footer__support support">
    </div>
        {% group_refs reference_links as grouped_links %}
        {% for group in grouped_links %}
        <div class="footer__socials socials">
            <div class="socials__title txt txt_font_osb txt_size_18">
                <span>{{ group.0.label }}</span>
            </div>
            <ul class="socials__list">
            {% for link in group %}
            <li class="socials__item">
                <a class="socials__link" href="{{ link.url }}">{{ link.reftype.icon_code|safe }}</a>
            </li>
            {% endfor %}
            </ul>
        </div>
        {% endfor %}
  </div>
</footer>